name: agat_sp_kraken_assess_liftover
description: |-
  The script takes as input gtf produced by Kraken (lift-over tool).
  It will analyse the kraken_mapped attributes to calculate the mapped percentage of each mRNA.
  According to a threshold (0 by default), gene with a mapping percentage over that value will be reported.
  A plot nammed geneMapped_plot.pdf is performed to visualize the result.
  /!\ The script handles chimeric files (i.e containg gene part mapped on the template genome and others on the de-novo one)
  /!\/!\ If the file is complete (containing kraken_mapped="TRUE" and kraken_mapped="FALSE" attributes),
  the script calcul the real percentage length that has been mapped.
  Else the calcul is only based on feature with kraken_mapped="TRUE" attributes.
  So in this case the result most of time will be 100%.
  /!\/!\/!\ We met rare cases where Kraken mapped a feature to several locations of the de-novo genome.
  As result we could end up with mapping over > 100%. We report them as 100% mapped in the plot
  and a warning is raised to allow to check thoses cases.
usage: |-
  agat_sp_kraken_assess_lift_coverage --gtf infile.gtf [ -o outfile ]
  agat_sp_kraken_assess_lift_coverage --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_kraken_assess_liftover.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_kraken_assess_lift_coverage.pl
arguments:
- name: -gtf
  type: file
  description: Input gtf file produced by Kraken.
  required: true
- name: --threshold
  type: integer
  description: Gene mapping percentage over which a gene must be reported. By default
    the value is 0.
  required: true
  alternatives: -t
- name: --verbose
  type: boolean_true
  description: Verbose information.
  alternatives: -v
- name: --plot
  type: boolean_true
  description: Allows to create an histogram in pdf. It shows the distribution of
    percentage of gene length mapped.
  alternatives: --p
- name: --outfile
  type: file
  description: Output GFF file.  If no output file is specified, the output will be
    written to STDOUT.
  required: true
  alternatives:
  - -o
  - --output
  - --out
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: false
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
