name: agat_sq_rename_seqid
description: "The script aims to modify seqid (1st column) of a GFF/GTF file efficiently.
  \nIndeed, when the number of chromosomes or scaffolding is large, \nreplacement
  using e.g. sed command can be time-consuming. \nYou must provide a file (tsv or
  csv) without header and with \none renaming information by line: The first value
  is the original sequence identifier (1st column of the GFF/GTF file), \nthe second
  value is the new sequence identifier to use.\n\n\nnumber of chromosomes or scaffolding
  is large, sed replacement is time-consuming"
usage: |-
  agat_sq_rename_seqid.pl --gff input.gff --tsv input.tsv [ -o output.gff3 ]
  agat_sq_rename_seqid.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sq_rename_seqid.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sq_rename_seqid.pl
arguments:
- name: --gff
  type: file
  description: 'STRING: Input GTF/GFF file.'
  required: yes
- name: --tsv
  type: file
  description: 'STRING: Input tsv file'
  required: yes
- name: --csv
  type: file
  description: 'BOLEAN: Inform the script that the tsv input file is actually a csv
    (coma-separated).'
  required: no
- name: --verbose
  type: boolean_true
  description: 'BOLEAN: Add verbosity'
  alternatives: -v
- name: --output
  type: file
  description: 'STRING: Output file. If no output file is specified, the output will
    be written to STDOUT. The result is in tabulate format.'
  required: yes
  alternatives: -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
