name: agat_convert_genscan2gff
description: |-
  The script takes a genscan file as input, and will translate it in gff format.
  The genscan format is described here: http://genome.crg.es/courses/Bioinformatics2003_genefinding/results/genscan.html
  /!\ vvv Known problem vvv /!\
  You must have submited only DNA sequence, wihtout any header!!
  Indeed the tool expects only DNA sequences and does not crash/warn if an header
  is submited along the sequence.
  e.g If you have an header ">seq" s-e-q are seen as the 3 first nucleotides of the sequence.
  Then all prediction location are shifted accordingly.
  (checked only on the online version http://argonaute.mit.edu/GENSCAN.html. I don't
  know if there is the same pronlem elsewhere.)
  /!\ ^^^ Known problem ^^^^ /!\
usage: |-
  agat_convert_genscan2gff.pl --genscan infile.bed [ -o outfile ]
  agat_convert_genscan2gff.pl -h
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_convert_genscan2gff.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_convert_genscan2gff.pl
arguments:
- name: --genscan
  type: file
  description: Input genscan bed file that will be convert.
  required: true
  alternatives: -g
- name: --seqid
  type: string
  description: 'String - Sequence ID. [default: unknown]'
  required: false
- name: --verbose
  type: boolean_true
  description: add verbosity
  alternatives: -v
- name: --outfile
  type: file
  description: Output GFF file. If no output file is specified, the output will be
    written to STDOUT.
  required: true
  alternatives:
  - -o
  - --output
  - --out
  - --gff
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: false
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
