name: agat_sp_add_intergenic_regions
description: |-
  The script aims to add intergenic features (intergenic_region) to gtf/gff file.
  The intergenic regions are deduced from gene features (feature type gene from the 3rd column).
usage: |-
  agat_sp_add_intergenic_regions.pl --gff infile --out outFile
  agat_sp_add_intergenic_regions.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_add_intergenic_regions.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_add_intergenic_regions.pl
arguments:
- name: --gff
  type: file
  description: Input GTF/GFF file.
  required: yes
  alternatives:
  - -f
  - --ref
- name: --output
  type: file
  description: Output file (default GFF3 - see config to modify output format).
  required: yes
  alternatives:
  - --out
  - -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives yo the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
- name: --verbose
  type: boolean_true
  description: Add verbosity
  alternatives: -v
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
