name: agat_sp_filter_feature_from_keep_list
description: |-
  The script aims to keep records based on a keeplist.
  The default behaviour is to look at the features's ID. If the feature has an ID
  (case insensitive) listed among the keeplist it will be kept along with all
  related features (the whole record is kept. A record represent all features linked
  by relationship e.g. gene+transcript+exon+cds of a same locus).
usage: |-
  agat_sp_filter_feature_from_keep_list.pl --gff infile.gff --keep_list file.txt  [ --output outfile ]
  agat_sp_filter_feature_from_keep_list.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_filter_feature_from_keep_list.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_filter_feature_from_keep_list.pl
arguments:
- name: --reffile
  type: file
  description: Input GFF3 file that will be read
  required: true
  alternatives:
  - -f
  - --gff
  - -ref
- name: --type
  type: string
  description: 'primary tag option, case insensitive, list. Allow to specied the feature
    types that will be handled. You can specified a specific feature by given its
    primary tag name (column 3) as: cds, Gene, MrNa You can specify directly all the
    feature of a particular level: level2=mRNA,ncRNA,tRNA,etc level3=CDS,exon,UTR,etc
    By default all feature are taking into account. fill the option by the value "all"
    will have the same behaviour.'
  required: true
  alternatives:
  - -p
  - -l
- name: --keep_list
  type: string
  description: Keep list. One value per line.
  required: true
  alternatives: --kl
- name: --attribute
  type: string
  description: 'Attribute tag to specify the attribute to analyse. Case sensitive.
    Default: ID'
  required: false
  alternatives: -a
- name: --output
  type: file
  description: Output GFF file.  If no output file is specified, the output will be
    written to STDOUT.
  required: true
  alternatives: -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: false
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
