name: agat_sp_keep_longest_isoform
description: |-
  The script aims to filter isoforms when present. For a locus:
  - when all isoforms have CDS we keep the one with the longest CDS.
  - when some isoforms have CDS some others not, we keep the one with the longest CDS.
  - when none of the isoforms have CDS, we keep the one with the longest concatenated exons.
usage: |-
  agat_sp_keep_longest_isoform.pl -gff file.gff  [ -o outfile ]
  agat_sp_keep_longest_isoform.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_keep_longest_isoform.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_keep_longest_isoform.pl
arguments:
- name: --gff
  type: file
  description: GTF/GFF file.
  required: yes
  alternatives: -f
- name: --output
  type: file
  description: File where will be written the result. If no output file is specified,
    the output will be written to STDOUT.
  required: yes
  alternatives: -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
