name: agat_sp_flag_short_introns_ebi
description: |-
  The script flags records that contain short introns (default 10bp) within coding sequences (CDS) with the <pseudo> attribute and changes the <product> attribute into a <note> attribute.
  This is useful for avoiding ERROR messages when submitting data to the EBI.
  (Typical EBI error message: ERROR: Intron usually expected to be at least 10 nt long. Please check the accuracy.)
usage: |-
  agat_sp_flag_short_introns_ebi.pl --gff infile --out outfile
  agat_sp_flag_short_introns_ebi.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_flag_short_introns_ebi.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_flag_short_introns_ebi.pl
arguments:
- name: -reffile
  type: file
  description: Input GTF/GFF file.
  required: yes
  alternatives:
  - --gff
  - -f
  - --ref
- name: --intron_size
  type: integer
  description: Minimum intron size, default 10. All genes with an intron < of this
    size will be flagged with the pseudo attribute (the value will be the size of
    the smallest intron found within the incriminated gene)
  required: no
  alternatives: -i
- name: --output
  type: file
  description: Output gff3 file where the result will be printed.
  required: yes
  alternatives:
  - --out
  - -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
