name: agat_sp_extract_attributes
description: |-
  The script takes a gtf/gff file as input.
  The script allows to extract choosen attributes of all or specific feature types.
  The 9th column of a gff/gtf file contains a list of attributes.
  An attribute (gff3) looks like that tag=value
usage: |-
  agat_sp_extract_attributes.pl --gff file.gff  --att locus_tag,product,name -p level2,cds,exon [ -o outfile ]
  agat_sp_extract_attributes.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_extract_attributes.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_extract_attributes.pl
arguments:
- name: --gff
  type: file
  description: Input GTF/GFF file.
  required: yes
  alternatives: -f
- name: -l
  type: string
  description: 'primary tag option, case insensitive, list. Allow to specied the feature
    types that will be handled. You can specified a specific feature by given its
    primary tag name (column 3) as: cds, Gene, MrNa You can specify directly all the
    feature of a particular level: level2=mRNA,ncRNA,tRNA,etc level3=CDS,exon,UTR,etc
    By default all feature are taking in account. fill the option by the value "all"
    will have the same behaviour.'
  required: yes
  alternatives:
  - -p
  - -t
- name: --attribute
  type: string
  description: attribute tag. The value of the attribute tag specified will be extracted
    from the feature type specified by the option -p. List of attributes must be coma
    separated.
  required: yes
  alternatives:
  - --att
  - -a
- name: --merge
  type: file
  description: By default the values of each attribute tag is writen in its dedicated
    file. To write the values of all tags in only one file use this option.
  required: no
  alternatives: -m
- name: -d
  type: boolean_true
  description: By default when an attribute is not found for a feature, a dot (.)
    is reported. If you don't want anything to be printed in such case use this option.
- name: --outfile
  type: file
  description: Output GFF file.  If no output file is specified, the output will be
    written to STDOUT.
  required: yes
  alternatives:
  - -o
  - --output
  - --out
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
