name: agat_sp_fix_cds_phases
description: "This script aims to fix the CDS phases.\nThe script is compatible with
  incomplete gene models (Missing start, CDS\nmultiple of 3 or not, i.e. with offset
  of 1 or 2) and + and - strand.\n\nHow it works?  \n\nAGAT uses the fasta sequence
  to verify the CDS frame.\nIn case the CDS start by a start codon the phase of the
  first CDS piece is set to 0.\nIn the case there is no start codon and: \n- If there
  is only one stop codon in the sequence and it is located at the last position, the
  phase of the first CDS piece is set to 0.\n- If there is no stop codon, the phase
  of the first CDS piece is set to 0 (because sequence can be translated without premature
  stop codon).\n- If there is/are stop codon(s) in the middle of the sequence we re-execute
  the check with an offset of +2 nucleotides:\n- If there is only one stop codon in
  the sequence and it is located at the last position, the phase of the first CDS
  piece is set to 0.\n- If there is no stop codon, the phase of the first CDS piece
  is set to 0 (because sequence can be translated without premature stop codon).\n-
  If there is/are stop codon(s) in the middle of the sequence we re-execute the check
  with an offset of +1 nucleotide:\n- If there is only one stop codon in the sequence
  and it is located at the last position, the phase of the first CDS piece is set
  to 0.\n- If there is no stop codon, the phase of the first CDS piece is set to 0
  (because sequence can be translated without premature stop codon).\n- If there is/are
  still stop codon(s) we keep original phase and throw a warning. In this last case
  it means we never succeded to make a translation without premature stop codon in
  all the 3 possible phases.\nThen in case of CDS made of multiple CDS pieces (i.e.
  discontinuous feature), the rest of the CDS pieces will be checked accordingly to
  the first CDS piece.\n\nWhat is a phase?  \n\nFor features of type \"CDS\", the
  phase indicates where the next codon begins\nrelative to the 5' end (where the 5'
  end of the CDS is relative to the strand\nof the CDS feature) of the current CDS
  feature. For clarification the 5' end\nfor CDS features on the plus strand is the
  feature's start and and the 5' end\nfor CDS features on the minus strand is the
  feature's end. The phase is one of\nthe integers 0, 1, or 2, indicating the number
  of bases forward from the start\nof the current CDS feature the next codon begins.
  A phase of \"0\" indicates that\na codon begins on the first nucleotide of the CDS
  feature (i.e. 0 bases forward),\na phase of \"1\" indicates that the codon begins
  at the second nucleotide of this\nCDS feature and a phase of \"2\" indicates that
  the codon begins at the third\nnucleotide of this region. Note that \"Phase\" in
  the context of a GFF3 CDS\nfeature should not be confused with the similar concept
  of frame that is also a\ncommon concept in bioinformatics. Frame is generally calculated
  as a value for\na given base relative to the start of the complete open reading
  frame (ORF) or\nthe codon (e.g. modulo 3) while CDS phase describes the start of
  the next codon\nrelative to a given CDS feature.  \nThe phase is REQUIRED for all
  CDS features."
usage: |-
  agat_sp_fix_cds_phases.pl --gff infile.gff -f fasta [ -o outfile ]
  agat_sp_fix_cds_phases.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_fix_cds_phases.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_fix_cds_phases.pl
arguments:
- name: --gff
  type: file
  description: Input GTF/GFF file.
  required: true
  alternatives:
  - -g
  - -ref
- name: --fasta
  type: file
  description: Input fasta file.
  required: true
  alternatives:
  - -f
  - --fa
- name: --verbose
  type: boolean_true
  description: Add verbosity.
  alternatives: -v
- name: --output
  type: file
  description: Output GFF file.  If no output file is specified, the output will be
    written to STDOUT.
  required: true
  alternatives: -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: false
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
