name: agat_sp_fix_overlaping_genes
description: |-
  Check a GTF/GFF annotation file to find cases where different gene features
  have CDS that overlap. In this case the gene features will be merged in only one.
  One gene is chosen as reference, and the mRNA from the other gene will be linked to it.
  So, it creates isoforms.
usage: |-
  agat_sp_fix_overlaping_genes.pl -f infile  [-o outfile]
  agat_sp_fix_overlaping_genes.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_fix_overlaping_genes.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_fix_overlaping_genes.pl
arguments:
- name: --file
  type: file
  description: Input GTF/GFF file.
  required: yes
  alternatives:
  - -f
  - --gff3
  - --gff
- name: --merge
  type: boolean_true
  description: 'Bolean: Merge/add the attributes of gene feature that are merged (except
    ID and Parent).'
  alternatives: -m
- name: --outfile
  type: file
  description: Output file. If none given, will be display in standard output.
  required: yes
  alternatives:
  - -o
  - --out
  - --output
  direction: output
- name: --verbose
  type: boolean_true
  description: 'BOLEAN: Add verbosity.'
  alternatives: -v
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
