name: agat_sp_move_attributes_within_records
description: |-
  The script aims to keep move attributes within a record e.g. from Level1 to Level2 and/or Level3 features; and / or from Level2 to Level2 or Level3 features; and / or from Level3 to Level3 features.
  Example of L1 feature: gene
  Example of L2 featrue
usage: |-
  agat_sp_move_attributes_within_records.pl --gff infile.gff --feature_copy mRNA  --feature_paste CDS --attribute Dbxref,Ontology [ --output outfile ]
  agat_sp_move_attributes_within_records.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_move_attributes_within_records.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_move_attributes_within_records.pl
arguments:
- name: --reffile
  type: file
  description: Input GFF3 file that will be read
  required: yes
  alternatives:
  - -f
  - --gff
  - -ref
- name: --feature_copy
  type: string
  description: 'primary tag (feature type) option to list from which feature we will
    copy the attributes, case insensitive.  You can specified a feature (or a coma
    separated list) by giving its primary tag / feature type (column 3) value as:
    cds, Gene, MrNa, etc You can specify directly all the feature of a particular
    level: level2=mRNA,ncRNA,tRNA,etc level3=CDS,exon,UTR,etc By default all level2
    feature are used.'
  required: no
  alternatives: --fc
- name: --feature_paste
  type: string
  description: 'primary tag (feature type) option to list to which feature we will
    paste the attributes, case sensitive.  You can specified a feature (or a coma
    separated list) by giving its primary tag / feature type (column 3) value as:
    cds, Gene, MrNa, etc You can specify directly all the feature of a particular
    level: level2=mRNA,ncRNA,tRNA,etc level3=CDS,exon,UTR,etc By default all feature
    level3 are used.'
  required: no
  alternatives: --fp
- name: --attribute
  type: string
  description: 'Attribute that will be copied and pasted. Case sensitive. You can
    specified an attribute (or a coma separated list) by giving its attribute tag
    value (column9) as: Ontology, Dbxref, etc Default: all_attributes /!\ <all_attributes>
    is a specific parameter meaning all the attributes will be use.'
  required: no
  alternatives:
  - -a
  - --tag
  - --att
- name: --output
  type: file
  description: Output GFF file.  If no output file is specified, the output will be
    written to STDOUT.
  required: yes
  alternatives: -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
