name: agat_sp_filter_record_by_coordinates
description: |-
  The script aims to filter the records to keep only those contained within coordinates
  defined in an input csv file.
  A record can be a feature or a set of features with part-of relationships.
  By default we keep records overlapping the coordinates. The --exclude parameter
  allows to keep only record fully contained within the coordinates.

  ! With default paramater, an exon out of the coordinates can be kept if the gene
  it is part of is overlaping the coordinates.
usage: |-
  agat_sp_filter_record_by_coordinates.pl --gff infile.gff --tsv coordinates.tsv [ --output outfile ]
  agat_sp_filter_record_by_coordinates.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_filter_record_by_coordinates.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_filter_record_by_coordinates.pl
arguments:
- name: --input
  type: file
  description: Input GTF/GFF file
  required: yes
  alternatives:
  - -i
  - --gtf
  - --gff
- name: --coordinates
  type: file
  description: String - tsv file containing the coordinates. Coordinates must be one
    per line. Each line must contain 3 fields separated by a tabulation. Field1 is
    the sequence id Field2 is the start coordinate (included) Field3 is the end coordinate
    (included)
  required: yes
  alternatives:
  - --tsv
  - -r
  - --ranges
- name: --exclude
  type: boolean_true
  description: Select only the features fully containined within the coordinates,
    exclude the overlapping ones.
  alternatives: -e
- name: --output
  type: string
  description: Output folder.
  required: yes
  alternatives: -o
  direction: output
- name: --verbose
  type: boolean_true
  description: Verbosity.
  alternatives: -v
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
