name: agat_sp_manage_UTRs
description: |-
  Detect the genes containing too much UTR's exon according to a choosen threshold.
  If no UTR option (3, 5, 3 and 5, both) is given the threshold will be not used.
  option 3 and 5 together is different of "both". In the first case the gene is discarded if either the 3' or the 5' UTR contains more exon than the threshold given.
  In the second case, will be discarded only the genes where the addition of UTR's exon of both side is over the threshold given.
usage: |-
  agat_sp_manage_UTRs.pl --ref infile --three --five -p --out outFile
  agat_sp_manage_UTRs.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_manage_UTRs.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_manage_UTRs.pl
arguments:
- name: --reffile
  type: file
  description: Input GTF/GFF file.
  required: true
  alternatives:
  - --gff
  - --ref
  - -f
- name: --number
  type: integer
  description: Threshold of exon's number of the UTR. Over or equal to this threshold,
    the UTR will be discarded. Default value is 5.
  required: true
  alternatives:
  - -n
  - -t
  - --nb
- name: --tree_prime_utr
  type: boolean_true
  description: The threshold of the option <n> will be applied on the 3'UTR.
  alternatives:
  - '-3'
  - --three
- name: --five_prime_utr
  type: boolean_true
  description: The threshold of the option <n> will be applied on the 5'UTR.
  alternatives:
  - '-5'
  - --five
- name: --both
  type: boolean_true
  description: The threshold of the option <n> will be applied on genes where the
    number of UTR exon (3' and 5' additioned) is over it.
  alternatives:
  - -b
  - --bs
- name: --plot
  type: boolean_true
  description: Allows to create an histogram in pdf of UTR sizes distribution.
  alternatives: --p
- name: --output
  type: file
  description: Output gff3 file where the gene incriminated will be write.
  required: true
  alternatives:
  - --out
  - -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: false
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
