name: agat_sp_fix_features_locations_duplicated
description: |-
  The script aims to modify/remove feature with duplicated locations. Even if it
  not an error by itself in a gtf/gff file, it becomes problematic when submitting
  the file to ENA (after convertion).
  To modify locations, AGAT modify the UTRs (when available) by shortening them by 1 bp (and consequently the Parent features and the exons accordingly)

  * Case1: When isoforms have identical exon structures, AGAT removes duplicates by keeping the one with longest CDS;
  * Case2: When l2 (e.g. mRNA) from different gene identifier have identical exon but no CDS at all, AGAT removes one duplicate);
  * Case3: When l2 (e.g. mRNA) from different gene identifier have identical exon and CDS structures, AGAT removes duplicates by keeping the one with longest CDS);
  * Case4: When l2 (e.g. mRNA) from different gene identifier have identical exon structures and different CDS structures, AGAT reshapes UTRs to modify mRNA and gene locations);
  * Case5: When l2 (e.g. mRNA) from different gene identifier overlap but have different exon structure. In that case AGAT modified the gene locations by clipping UTRs;
usage: |-
  agat_sp_fix_features_locations_duplicated.pl --gff infile  [-o outfile]
  agat_sp_fix_features_locations_duplicated.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_fix_features_locations_duplicated.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_fix_features_locations_duplicated.pl
arguments:
- name: --file
  type: file
  description: Input GTF/GFF file.
  required: true
  alternatives:
  - -f
  - --gff3
  - --gff
- name: --model
  type: string
  description: 'To select cases you want to fix. By default all are used. To select
    specific cases write e.g. --model 1,4,5  Case1: When isoforms have identical exon
    structures AGAT removes duplicates by keeping the one with longest CDS; Case2:
    When l2 (e.g. mRNA) from different gene identifier have identical exon but no
    CDS at all (AGAT removes one duplicate); Case3: When l2 (e.g. mRNA) from different
    gene identifier have identical exon and CDS structures (AGAT removes duplicates
    by keeping the one with longest CDS); Case4: When l2 (e.g. mRNA) from different
    gene identifier have identical exon structures and different CDS structures (AGAT
    reshapes UTRs to modify mRNA and gene locations); Case5: When l2 (e.g. mRNA) from
    different gene identifier overlap but have different exon structure. In that case
    AGAT modified the gene locations by clipping UTRs;'
  required: true
  alternatives: -m
- name: --verbose
  type: boolean_true
  description: Add verbosity.
  alternatives: -v
- name: --outfile
  type: file
  description: Output file. If none given, will be display in standard output.
  required: true
  alternatives:
  - -o
  - --out
  - --output
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: false
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
