name: agat_sp_separate_by_record_type
description: |-
  The script will separate the features from the gff input file into different files according to
  the record type. A record represent all features linked collectively by Parent/ID relationships.
  (e.g gene + mrna + exon + cds + utr of a locus).

  a) When the record contains Level2 feature, the record type is the Level2 feature type (e.g tRNA,mRNA,ncRNA etc...)
  b) Some features do not have children (top and standalone level1 features) e.g. location,region,chromosome.
  In such case the record type is the level1 feature type.
usage: |-
  agat_sp_separate_by_record_type.pl -g infile.gff [ -o outfolder ]
  agat_sp_separate_by_record_type.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_separate_by_record_type.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_separate_by_record_type.pl
arguments:
- name: --gff
  type: file
  description: Input GTF/GFF file.
  required: yes
  alternatives:
  - -g
  - -ref
- name: --output
  type: string
  description: Output folder.  If no output folder provided, the default name will
    be <split_result>.
  required: yes
  alternatives: -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
