name: agat_sp_filter_feature_by_attribute_presence
description: |-
  The script aims to filter features according to attribute presence (9th column).
  If the attribute exists, the feature is discarded.
  Attribute are stored in the 9th column and have this shape: tag=value
  /!\ Removing a level1 or level2 feature will automatically remove all linked subfeatures, and
  removing all children of a feature will automatically remove this feature too.
usage: |-
  agat_sp_filter_feature_by_attribute_presence.pl --gff infile.gff -a <tag> [ --output outfile ]
  agat_sp_filter_feature_by_attribute_presence.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_filter_feature_by_attribute_presence.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_filter_feature_by_attribute_presence.pl
arguments:
- name: --reffile
  type: file
  description: Input GFF3 file that will be read
  required: yes
  alternatives:
  - -f
  - --gff
  - -ref
- name: --type
  type: string
  description: 'primary tag option, case insensitive, list. Allow to specied the feature
    types that will be handled. You can specified a specific feature by given its
    primary tag name (column 3) as: cds, Gene, MrNa You can specify directly all the
    feature of a particular level: level2=mRNA,ncRNA,tRNA,etc level3=CDS,exon,UTR,etc
    By default all feature are taking into account. fill the option by the value "all"
    will have the same behaviour.'
  required: yes
  alternatives:
  - -p
  - -l
- name: --attribute
  type: string
  description: String - Attributes tag specified will be used to filter the feature
    type (feature type can also be specified by the option -p).  List of attribute
    tags must be coma separated.
  required: yes
  alternatives:
  - --att
  - -a
- name: --flip
  type: boolean_true
  description: BOLEAN - In order to flip the test and keep features that do have the
    attribute and filter those without
- name: --output
  type: file
  description: Output GFF file.  If no output file is specified, the output will be
    written to STDOUT.
  required: yes
  alternatives: -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: no
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
