name: agat_sp_filter_feature_by_attribute_value
description: "The script aims to filter features according to attribute value (9th
  column).\n- If the attribute exists and the value do not pass the test, the feature
  is written into <output>.\n- If the attribute exists and the value pass the test,
  the feature is discarded and written into <output>_discarded.gff.\n- If the attribute
  tag is missing (test cannot be applyed), the feature will be written into <output>
  by default. If --na_aside parameter \nis activated then it will be written into
  <output>_na.gff.\n\nAttribute are stored in the 9th column and have this shape:
  tag=value\n/!\\ Removing a level1 or level2 feature will automatically remove all
  linked subfeatures.\n/!\\ Removing all children of a feature will automatically
  remove this feature too (excepted if --keep_parental is activated).\n/!\\ If --keep_parental
  is not activated and --na_aside is activated, and all level3 features of a record
  are split between both <output>_na.gff and <output>_discarded.gff, \nthen the parental
  level1 and level2 features are removed and will end up in the <output>_na.gff file
  only."
usage: |-
  agat_sp_filter_feature_by_attribute_value.pl --gff infile.gff --value 1 -t "=" [ --output outfile ]
  agat_sp_filter_feature_by_attribute_value.pl --help
links:
  homepage: https://agat.readthedocs.io
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_filter_feature_by_attribute_value.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references:
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands:
  - agat_sp_filter_feature_by_attribute_value.pl
arguments:
- name: --reffile
  type: file
  description: Input GFF3 file that will be read
  required: true
  alternatives:
  - -f
  - --gff
  - -ref
- name: --attribute
  type: string
  description: 'Attribute tag to specify the attribute to analyse (attribute example:
    tag=value).'
  required: true
  alternatives: -a
- name: --type
  type: string
  description: 'primary tag option, case insensitive, list. Allow to specied the feature
    types that will be handled. You can specified a specific feature by given its
    primary tag name (column 3) as: cds, Gene, MrNa You can specify directly all the
    feature of a particular level: level2=mRNA,ncRNA,tRNA,etc level3=CDS,exon,UTR,etc
    By default all feature are taking into account. fill the option by the value "all"
    will have the same behaviour.'
  required: true
  alternatives:
  - -p
  - -l
- name: --value
  type: string
  description: Value(s) to check in the attribute. Case sensitive. List of values
    must be coma separated.
  required: true
- name: --value_insensitive
  type: boolean_true
  description: Bolean. Deactivated by default. When activated the values provided
    by the --value parameter are handled case insensitive.
- name: --na_aside
  type: file
  description: Bolean. Deactivated by default. By default if the attribute tag on
    which the filter is based is missing, the feature will be written into <output>.
    When activated, such features will be written into a separate file called <output>_na.gff.
  required: false
  direction: output
- name: --keep_parental
  type: boolean_true
  description: Bolean. Deactivated by default. When activated even if all child features
    have been removed, the parental one will be kept.
- name: --test
  type: string
  description: Test to apply (> < = ! >= <=). default value "=".  If you use one of
    these two character >, <, please don't forget to quote the parameter like that
    "<=" otherwise your terminal will complain. Only = and ! tests can be used to
    compare string values.
  required: false
  alternatives: -t
- name: --output
  type: file
  description: Output GFF file. If no output file is specified, the output will be
    written to STDOUT.
  required: true
  alternatives: -o
  direction: output
- name: --config
  type: file
  description: 'String - Input agat config file. By default AGAT takes as input agat_config.yaml
    file from the working directory if any,  otherwise it takes the orignal agat_config.yaml
    shipped with AGAT. To get the agat_config.yaml locally type: "agat config --expose".
    The --config option gives you the possibility to use your own AGAT config file
    (located elsewhere or named differently).'
  required: false
  alternatives: -c
resources:
- type: bash_script
  path: script.sh
engines:
- type: docker
  image: quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0
  setup:
  - type: docker
    run: 'agat --version | sed ''s/AGAT\s\(.*\)/agat: "\1"/'' > /var/software_versions.txt'
runners:
- type: executable
- type: nextflow
